language: node_js
node_js:
  - 0.10
install:
  - travis_retry yarn install

script:
  - node --version
  - npm --version
  - yarn --version
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm install -g travis-deploy-once semantic-release && travis-deploy-once "semantic-release"
